### ISSUE TITLE
JsonNavigationViewService

### ISSUE THREAD

**Issue by shovelbox** [WinUICommunity/WinUICommunity#11]
![image](https://github.com/WinUICommunity/WinUICommunity/assets/65446836/bb23a216-e6fd-4f76-8bb3-c0b43e2610fd)

How do I change font size and family font?

**Comment by ghost1372** [comment]
Hi,
for FontFamily you can override `ContentControlThemeFontFamily`, i should add a property for fontsize.
but i think you can also override TitleTextBlockStyle if possibile!

https://github.com/WinUICommunity/WinUICommunity/blob/7c281ffb40e562585ad8affec48f2a4937ff83b4/dev/LandingPages/LandingPages/AllLandingPage.xaml#L54C47-L54C66

https://github.com/WinUICommunity/WinUICommunity/blob/7c281ffb40e562585ad8affec48f2a4937ff83b4/dev/LandingPages/Themes/ItemTemplates.xaml#L68

https://github.com/WinUICommunity/WinUICommunity/blob/7c281ffb40e562585ad8affec48f2a4937ff83b4/dev/LandingPages/Themes/ItemTemplates.xaml#L61

**Comment by shovelbox** [comment]
👍

**Comment by ghost1372** [comment]
Hi @shovelbox 
your feature request added!
you can use **HeaderFontSize** property in AllLandingPage and **HeaderFontSize**, **HeaderSubtitleFontSize** in MainLandingPage.

also for changing fontsize in items (since this is a itemtemplate we can not use property) you can override fontsizes in App.xaml:

```
<x:Double x:Key="LandingItemTitleFontSize">12</x:Double>
 <x:Double x:Key="LandingItemSubtitleFontSize">16</x:Double>
```

you can access this features in next version which will be available soon

![image](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/374e8c01-732a-4ab6-817d-db5e5a15a454)

**Comment by shovelbox** [comment]
Why don't you have a font family setting?
