### ISSUE TITLE
Discussion: How to properly apply ThemeService to get dark mode system context menu?

### ISSUE THREAD

**Issue by Alloyd031** [WinUICommunity/WinUICommunity#30]

**Comment by ghost1372** [comment]
if you use our TitleBar Control, you dont need to do anything and you can have Dark/Light system context menu automatically.

![image](https://github.com/user-attachments/assets/cee821cf-da3f-46f7-b69c-09d14adb11a5)
 
Please note that with the release of WASDK v1.6, the title bar will be removed (because WASDK added a new TitleBar control)


if you have your own TitleBar, you can use our Helper Method

`GeneralHelper.SetPreferredAppMode(ElementTheme.Dark);`
