### ISSUE TITLE
Improve ThemeService

### ISSUE THREAD

**Issue by RoccoZero** [WinUICommunity/WinUICommunity#39]
Please make ThemeServiceBase it will not have this Nucs.JsonSettings2
since it bothers me, it creates a config file even if I set useAutoSave=false

I have my own way of saving data, so your way of saving doesn't suit me.

also this Nucs.JsonSettings2 uses Castle.Core and Newtonsoft.Json and this is another extra for me
instead of this you can use Microsoft.Extensions.Logging and System.Text.Json

**Comment by ghost1372** [comment]
Thank you for your suggestion.

I will check it, it might be a bug.  The last time I tested everything was working fine.

I tried to port NewtonSoft.Json to system.text.json before, but there were some problems, so I gave up due to lack of time.  But I will definitely do it whenever I have enough time.

**Comment by ghost1372** [comment]
@RoccoZero I removed **nucs.JsonSettings** from **Core**, and I internally wrote a simple configuration saver to handle the necessary requirements.
if you set **useAutoSave=false** No folder or file will be created and you can use your own method.
