### ISSUE TITLE
What do I do now that NativeMethods class was destroyed in 7.0.0?

### ISSUE THREAD

**Issue by MPITech** [WinUICommunity/WinUICommunity#44]
Why was NativeMethods obliterated in 7.0.0?  I have over 140 items to fix after updating to 7.0.0 and many are due to changes in NativeMethods with methods no longer existing, etc.  Can someone please point me to more info about this or how to correct the issues please?  Is there another library or namespace I should be using instead?  Thanks a lot, and please forgive me if this is not the right place for this, I couldn't find anywhere else to ask.  Thanks!

**Comment by ghost1372** [comment]
I am sorry for this.
Due to AOT support, we were forced to use CSWin32 library, and We removed the APIs available in the NativeMethods class.
you can use [cswin32](https://github.com/microsoft/cswin32) or you can just copy-paste NativeMethods into your project.
https://github.com/WinUICommunity/WinUICommunity/blob/407ef252c69d5e541af724be7119857498560fa0/dev/Core/NativeMethods/NativeMethods.cs

https://github.com/WinUICommunity/WinUICommunity/blob/407ef252c69d5e541af724be7119857498560fa0/dev/Core/NativeMethods/NativeValues.cs

**Comment by MPITech** [comment]
Thanks so much for your response.
